- id: doi:10.1021/acs.est.8b07203
  image: "images/GaleriaA.jpg"
  date: 2019-5-10
  extra-links:
    - type: manubot
      link: https://pubs.acs.org/doi/10.1021/acs.est.8b07203
  tags:
    - membranes
