- id: 10.1126/science.abh2283
  image: "images/logotipoCUBE.jpg"
  date: 2019-5-10
  extra-links:
    - type: website
      link: https://www.science.org/doi/10.1126/science.abh2283
  tags:
    - graphene
    - fiber
    - self-assembly
    - opinion
